# Generated by Django 5.2.3 on 2025-06-15 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', 'Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон')),
                ('polycoin_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс PolyCoin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', 'Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('course', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Курс')),
                ('polycoin_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс PolyCoin')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='users.curator', verbose_name='Куратор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
        ),
    ]
